### ISSUE TITLE
error out if new_trial variable not present 

### ISSUE THREAD

**Issue by jeremyforest** [neurogym/neurogym#11]
In pneumostomeopening.py, in the step function, if {'new_trial': new_trial} is absent then it error out. But there is no trial in this task and not sure how to solve that error (besides defining new_trial = False for all times in the step function). 

python neurogym/neurogym/envs/pneumostomeopening.py 
oxygen_level: 11
[2] 0.5 False {'new_trial': False}
Traceback (most recent call last):
  File "neurogym/neurogym/envs/pneumostomeopening.py", line 165, in <module>
    plot = plot_env(env, num_steps=100)
  File "/home/jeremy/anaconda3/envs/neurogym/lib/python3.7/site-packages/neurogym/utils/plotting.py", line 49, in plot_env
    def_act=def_act, model=model)
  File "/home/jeremy/anaconda3/envs/neurogym/lib/python3.7/site-packages/neurogym/utils/plotting.py", line 89, in run_env
    ob, rew, done, info = env.step(action)
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by gyyang** [comment]
Sorry for the delay. This should be fixed now, could you check again?

**Comment by jeremyforest** [comment]
Looks like its working great ! thanks!
