### ISSUE TITLE
problem with contrib envs registration

### ISSUE THREAD

**Issue by jeremyforest** [neurogym/neurogym#33]
Using ngym_usage
running `python training/RL_train.py` on pneumostomeopening env
 ```

Traceback (most recent call last):
  File "/home/jeremy/anaconda3/envs/neurogym/lib/python3.7/site-packages/gym/envs/registration.py", line 121, in spec
    return self.env_specs[id]
KeyError: 'Pneumostomeopening-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "training/RL_train.py", line 229, in <module>
    train_network(envid)
  File "training/RL_train.py", line 111, in train_network
    env = DummyVecEnv(make_envs)  # Less efficient but more robust
  File "/home/jeremy/anaconda3/envs/neurogym/lib/python3.7/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 23, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/home/jeremy/anaconda3/envs/neurogym/lib/python3.7/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 23, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "training/RL_train.py", line 51, in _init
    env = gym.make(env_id, **kwargs)
  File "/home/jeremy/anaconda3/envs/neurogym/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/jeremy/anaconda3/envs/neurogym/lib/python3.7/site-packages/gym/envs/registration.py", line 89, in make
    spec = self.spec(path)
  File "/home/jeremy/anaconda3/envs/neurogym/lib/python3.7/site-packages/gym/envs/registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: Pneumostomeopening-v0


```

Checking environments:

> ['AntiReach-v0', 'Bandit-v0', 'ContextDecisionMaking-v0', 'DawTwoStep-v0', 'DelayComparison-v0', 'DelayMatchCategory-v0', 'DelayMatchSample-v0', 'DelayMatchSampleDistractor1D-v0', 'DelayPairedAssociation-v0', 'DualDelayMatchSample-v0', 'EconomicDecisionMaking-v0', 'GoNogo-v0', 'HierarchicalReasoning-v0', 'IntervalDiscrimination-v0', 'MotorTiming-v0', 'MultiSensoryIntegration-v0', 'Null-v0', 'OneTwoThreeGo-v0', 'PerceptualDecisionMaking-v0', 'PerceptualDecisionMakingDelayResponse-v0', 'PostDecisionWager-v0', 'ProbabilisticReasoning-v0', 'PulseDecisionMaking-v0', 'Reaching1D-v0', 'Reaching1DWithSelfDistraction-v0', 'ReachingDelayResponse-v0', 'ReadySetGo-v0', 'SingleContextDecisionMaking-v0', 'SpatialSuppressMotion-v0', 'contrib.Pneumostomeopening-v0']

If I copy pneumostomeopening.py temporarily in the neurogym/envs instead of neurogym/emvs/contrib it runs without problem. 

In registration.py, reverting env_prefix to None for contrib envs  solves it.  Not sure why the env_prefix is needed ? Will removing break something else ?

**Comment by jeremyforest** [comment]
if it doesn't break anything else and that is the right change to make I can push to dev and then master. Just need a validation on this.

**Comment by gcroci2** [comment]
Is this still relevant? Otherwise, we can close it @nacloos
